# -*- coding: utf-8 -*-
"""Test.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uAQBhJcYvh91cqbUO04Hkoy5rKHrSvnW

# AI 품질 평가 모델 학습 - klue/roberta-base

이 노트북은 AI 응답 품질 평가를 위한 Multi-label Classification 모델을 학습합니다.

**평가 기준 (9개)**:

- linguistic_acceptability (언어적 수용성)
- consistency (일관성)
- interestingness (흥미로움)
- unbias (편향 없음)
- harmlessness (무해성)
- no_hallucination (환각 없음)
- understandability (이해 가능성)
- sensibleness (합리성)
- specificity (구체성)

## 1. 라이브러리 설치 및 임포트
"""

from google.colab import drive
drive.mount('/content/drive/')

import pandas as pd
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
)
from sklearn.metrics import accuracy_score, f1_score, classification_report
from tqdm.auto import tqdm
import warnings

warnings.filterwarnings('ignore')

# GPU 확인
device = torch.device('cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu')
print(f"Using device: {device}")

"""## 2. 설정"""

# 모델 및 학습 설정
MODEL_NAME = "klue/roberta-base"
MAX_LENGTH = 330
BATCH_SIZE = 128
LEARNING_RATE = 2e-5
NUM_EPOCHS = 3
SEED = 42

# 평가 기준 (타겟 컬럼)
CRITERIA = [
    'linguistic_acceptability',
    'consistency',
    'interestingness',
    'unbias',
    'harmlessness',
    'no_hallucination',
    'understandability',
    'sensibleness',
    'specificity'
]
NUM_LABELS = len(CRITERIA)

# 시드 고정
torch.manual_seed(SEED)
np.random.seed(SEED)

"""## 3. 데이터 로드"""

# # unzip
# unzip_path = '/content/drive/MyDrive/AI_data/data.zip'
# !unzip -qq {unzip_path} -d /content/drive/MyDrive/AI_data/

# Training 및 Validation 데이터 로드 (aggregated 버전 사용 - majority voting 결과)
train_df = pd.read_csv('/content/drive/MyDrive/AI_data/data/train/training_all_aggregated.csv', encoding='utf-8-sig')
val_df = pd.read_csv('/content/drive/MyDrive/AI_data/data/val/validation_all_aggregated.csv', encoding='utf-8-sig')

print(f"Training 데이터: {len(train_df):,}개")
print(f"Validation 데이터: {len(val_df):,}개")

train_df['topic'].value_counts()

# 데이터 확인
train_df[train_df['topic']=='엔터테인먼트, 오락, 예술'].head(10)

# 1. 지표 매핑 딕셔너리 생성 (컬럼명: 한글 설명)
quality_metrics = {
    "linguistic_acceptability_majority": "언어학적 수용성",
    "consistency_majority": "일관성",
    "interestingness_majority": "흥미성",
    "unbias_majority": "비편향성",
    "harmlessness_majority": "무해성",
    "no_hallucination_majority": "정보 근거성",
    "understandability_majority": "이해 가능성",
    "sensibleness_majority": "답변의 적절성",
    "specificity_majority": "답변의 구체성"
}

target_topic = '엔터테인먼트, 오락, 예술'
entertainment_df = train_df[train_df['topic'] == target_topic]

for i, row in entertainment_df.tail(5).iterrows():
    print(f"[{i+1}번 데이터]")
    print(f"🙋 질문: {row['human_question']}")
    print(f"🤖 응답: {row['bot_response']}")
    print("\n[📊 품질 평가 상세]")

    # 9가지 지표를 순회하며 출력
    for col, name in quality_metrics.items():
        status = "✅ Pass" if row[col] == 1 else "❌ Fail"
        print(f" - {name}: {status}")

    print("-" * 50)

# 컬럼 확인
print("컬럼 목록:")
print(train_df.columns.tolist())

def create_hard_negatives(df, negative_ratio=0.2, seed=42):
    """기존 데이터의 답변을 섞어 '내용이 틀린' 부정 샘플을 생성합니다."""
    n_samples = int(len(df) * negative_ratio)
    neg_df = df.sample(n=n_samples, random_state=seed).copy()

    # 다른 행의 답변을 무작위로 가져와 매칭 (내용 불일치 유도)
    shuffled_responses = df.sample(n=n_samples, random_state=seed+1)['bot_response'].values
    neg_df['bot_response'] = shuffled_responses

    # 모든 품질 지표 라벨을 0(Fail)으로 설정
    for criterion in CRITERIA:
        neg_df[f"{criterion}_majority"] = 0

    print(f"✅ {n_samples}개의 Hard Negative 데이터 생성 완료!")
    return neg_df

import pandas as pd
from tqdm import tqdm
import numpy as np # 🆕 추가 (랜덤 시드 등을 위해 필요)

# 1. 기존 함수 유지
def merge_dialogue_context(df, window_size=2):

    df = df.sort_values(['conversation_id', 'utterance_index']).reset_index(drop=True)
    contexts = []
    for i in tqdm(range(len(df)), desc="Merging Contexts"):
        current_row = df.iloc[i]
        c_id = current_row['conversation_id']
        history = df[(df['conversation_id'] == c_id) & (df.index < i)].tail(window_size)
        history_text = ""
        for _, h_row in history.iterrows():
            history_text += f"{h_row['human_question']} [SEP] {h_row['bot_response']} [SEP] "
        full_input = f"{history_text}{current_row['human_question']} [SEP] {current_row['bot_response']}"
        contexts.append(full_input)
    df['input_with_context'] = contexts
    return df

# 2. 🆕 [함수 추가] Hard Negative 생성 함수
def create_hard_negatives(df, negative_ratio=0.2, seed=42):
    """기존 데이터의 답변을 섞어 '내용이 틀린' 부정 샘플을 생성합니다."""
    n_samples = int(len(df) * negative_ratio)
    neg_df = df.sample(n=n_samples, random_state=seed).copy()

    # 다른 행의 답변을 무작위로 가져와 매칭 (내용 불일치 유도)
    shuffled_responses = df.sample(n=n_samples, random_state=seed+1)['bot_response'].values
    neg_df['bot_response'] = shuffled_responses

    # 모든 품질 지표 라벨을 0(Fail)으로 설정
    for criterion in CRITERIA:
        neg_df[criterion] = 0
    return neg_df

# --- 적용하기 ---

# [변경 포인트 1] 학습 데이터 확장
print("🛠️ Hard Negative 데이터 생성 및 학습 데이터 확장 중...")
hard_neg_df = create_hard_negatives(train_df, negative_ratio=0.2)
# 기존 train_df와 생성된 부정 데이터를 합칩니다.
extended_train_df = pd.concat([train_df, hard_neg_df], axis=0, ignore_index=True)

# [변경 포인트 2] 확장된 데이터셋(extended_train_df)으로 맥락 병합 실행
print("학습 데이터 맥락 병합 중 (부정 샘플 포함)...")
train_df = merge_dialogue_context(extended_train_df, window_size=2)

# 검증 데이터는 원본 그대로 유지 (평가의 객관성을 위해)
print("검증 데이터 맥락 병합 중...")
val_df = merge_dialogue_context(val_df, window_size=2)

"""## 4. 데이터 전처리"""

def preprocess_data(df: pd.DataFrame) -> pd.DataFrame:
    """데이터 전처리: 입력 텍스트 생성 및 결측치 처리"""
    df = df.copy()

    # 결측치 처리
    df['human_question'] = df['human_question'].fillna('')
    df['bot_response'] = df['bot_response'].fillna('')

    # 입력 텍스트 생성: [질문] + [SEP] + [응답]
    df['input_text'] = df['human_question'] + ' [SEP] ' + df['bot_response']

    # 타겟 컬럼 추출 (majority voting 결과)
    # 결과가 [1, 1, 0, 1, 0, 0, 1, 1, 1] 과 같은 리스트 형태로 저장됨
    target_cols = [f'{c}_majority' for c in CRITERIA]

    # 타겟 결측치 제거
    df = df.dropna(subset=target_cols)

    return df

train_df = preprocess_data(train_df)
val_df = preprocess_data(val_df)

print(f"전처리 후 Training 데이터: {len(train_df):,}개")
print(f"전처리 후 Validation 데이터: {len(val_df):,}개")

# 레이블 분포 확인
target_cols = [f'{c}_majority' for c in CRITERIA]

print("=" * 50)
print("레이블 분포 (Training)")
print("=" * 50)
for col in target_cols:
    pos_ratio = train_df[col].mean()
    print(f"{col}: {pos_ratio:.2%} positive")

"""## 5. Tokenizer 로드"""

# klue/roberta-base 토크나이저 로드
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

print(f"Tokenizer 로드 완료: {MODEL_NAME}")
print(f"Vocab size: {tokenizer.vocab_size:,}")

# 토크나이저 테스트
sample_text = train_df['input_with_context'].iloc[0]
print(f"샘플 텍스트:\n{sample_text}\n")

tokens = tokenizer(sample_text, truncation=True, max_length=MAX_LENGTH)
print(f"토큰 수: {len(tokens['input_ids'])}")

# 1. 새로운 'input_with_context' 기준 토큰 길이 계산
token_lengths = [len(tokenizer.encode(text, add_special_tokens=True)) for text in tqdm(train_df['input_with_context'], desc="Checking New Lengths")]

# 2. 통계치 확인
print(f"\n[📊 맥락 포함 토큰 통계]")
print(f" - 95th percentile: {np.percentile(token_lengths, 95)}")
print(f" - 99th percentile: {np.percentile(token_lengths, 99)}")
print(f" - 최대 길이: {np.max(token_lengths)}")

# 3. 데이터 저장 (내일 바로 불러와서 쓸 수 있게)
# 구글 드라이브 경로로 설정하세요.
train_df.to_csv('/content/drive/MyDrive/final_train_context.csv', index=False)
val_df.to_csv('/content/drive/MyDrive/final_val_context.csv', index=False)
print("\n✅ 최종 데이터셋 저장 완료!")

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm

# 1. 모든 input_text의 토큰 길이 계산 (시간이 조금 걸릴 수 있습니다)
token_lengths = [len(tokenizer.encode(text, add_special_tokens=True)) for text in tqdm(train_df['input_with_context'], desc="Calculating lengths")]

# 2. 통계치 계산
max_len = np.max(token_lengths)
mean_len = np.mean(token_lengths)
p95 = np.percentile(token_lengths, 95)
p99 = np.percentile(token_lengths, 99)

print(f"\n[📊 Token Length Statistics]")
print(f" - 전체 데이터 수: {len(token_lengths)}개")
print(f" - 최대 토큰 길이: {max_len}")
print(f" - 평균 토큰 길이: {mean_len:.2f}")
print(f" - 95% 데이터가 포함되는 길이: {p95}")
print(f" - 99% 데이터가 포함되는 길이: {p99}")

# 3. 분포 시각화
plt.figure(figsize=(12, 6))
sns.histplot(token_lengths, bins=50, color='teal', kde=True)
plt.axvline(p95, color='orange', linestyle='--', label=f'95th Percentile ({p95:.0f})')
plt.axvline(p99, color='red', linestyle='--', label=f'99th Percentile ({p99:.0f})')
plt.title('Token Length Distribution (Question + Answer)')
plt.xlabel('Number of Tokens')
plt.ylabel('Count')
plt.legend()
plt.show()

"""## 6. Dataset 클래스 정의"""

class QualityEvalDataset(Dataset):
    """AI 품질 평가 데이터셋"""

    def __init__(self, df: pd.DataFrame, tokenizer, max_length: int = 330):
        self.df = df.reset_index(drop=True)
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.target_cols = [f'{c}_majority' for c in CRITERIA]

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        text = row['input_with_context']
        labels = row[self.target_cols].values.astype(np.float32)

        # 토크나이즈
        encoding = self.tokenizer(
            text,
            truncation=True,
            max_length=self.max_length,
            padding='max_length',
            return_tensors='pt'
        )

        return {
            'input_ids': encoding['input_ids'].squeeze(0),
            'attention_mask': encoding['attention_mask'].squeeze(0),
            'labels': torch.tensor(labels, dtype=torch.float)
        }

# Dataset 생성
train_dataset = QualityEvalDataset(train_df, tokenizer, MAX_LENGTH)
val_dataset = QualityEvalDataset(val_df, tokenizer, MAX_LENGTH)

print(f"Train dataset size: {len(train_dataset):,}")
print(f"Val dataset size: {len(val_dataset):,}")

# Dataset 확인
sample = train_dataset[0]
print(f"input_ids shape: {sample['input_ids'].shape}")
print(f"attention_mask shape: {sample['attention_mask'].shape}")
print(f"labels shape: {sample['labels'].shape}")
print(f"labels: {sample['labels']}")

"""## 7. 모델 로드"""

# Multi-label Classification을 위한 모델 로드
model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=NUM_LABELS,
    problem_type="multi_label_classification"
)

model.to(device)
print(f"모델 로드 완료: {MODEL_NAME}")
print(f"파라미터 수: {sum(p.numel() for p in model.parameters()):,}")

"""## 8. 평가 지표 함수"""

def compute_metrics(eval_pred):
    """평가 지표 계산 (수정 완료 버전)"""
    predictions, labels = eval_pred

    # 1. Sigmoid 적용 후 0.5 기준으로 이진화
    # 예측값(logits)을 확률로 변환하고 0 또는 1로 결정합니다.
    predictions = torch.sigmoid(torch.tensor(predictions)).numpy()
    predictions = (predictions > 0.5).astype(int)
    labels = labels.astype(int)

    # 2. 공통 지표 계산
    # 전체 정확도: 9개 지표가 모두 일치해야 1점
    exact_match = np.all(predictions == labels, axis=1).mean()
    # 전체적인 균형을 보는 Micro/Macro F1
    micro_f1 = f1_score(labels, predictions, average='micro')
    macro_f1 = f1_score(labels, predictions, average='macro')

    metrics = {
        'exact_match': exact_match,
        'micro_f1': micro_f1,
        'macro_f1': macro_f1,
    }

    # 3. 각 기준(Criterion)별 세부 지표 계산 (하나의 루프에서 처리)
    # 가이드라인에 따라 정확도(acc)와 F1-score를 모두 기록합니다.
    for i, criterion in enumerate(CRITERIA):
        # 해당 지표 열만 추출
        pred_col = predictions[:, i]
        label_col = labels[:, i]

        # 기준별 정확도
        metrics[f'{criterion}_acc'] = (pred_col == label_col).mean()
        # 기준별 F1 (데이터 불균형 고려)
        metrics[f'{criterion}_f1'] = f1_score(label_col, pred_col, zero_division=0)

    return metrics

"""## 9. Trainer 설정 및 학습"""

# Training Arguments 설정
training_args = TrainingArguments(
    output_dir='./outputs/klue-roberta-base',
    num_train_epochs=NUM_EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE * 2,
    learning_rate=LEARNING_RATE,
    weight_decay=0.01,
    warmup_ratio=0.1,
    logging_dir='./logs',
    logging_steps=100,
    eval_strategy='epoch',
    save_strategy='epoch',
    load_best_model_at_end=True,
    metric_for_best_model='macro_f1',
    greater_is_better=True,
    report_to='none',  # wandb 사용 시 'wandb'로 변경
    seed=SEED,
    fp16=torch.cuda.is_available(),  # CUDA 사용 시 FP16 활성화
)

# Trainer 생성
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
)

# --- Step 3: 데이터셋 및 Trainer 갱신 ---

# 1. Dataset을 반드시 다시 생성해야 합니다 (가장 중요!)
# 이 코드가 실행되어야 'hard_neg_df'가 합쳐진 'train_df'가 모델의 입력 데이터셋으로 변환됩니다.
train_dataset = QualityEvalDataset(train_df, tokenizer, MAX_LENGTH)
val_dataset = QualityEvalDataset(val_df, tokenizer, MAX_LENGTH)

# 2. [선택사항] TrainingArguments 수정 (그대로 써도 되지만 추천 설정)
# 데이터가 늘어났으므로, 기존보다 조금 더 조심스럽게 학습하도록 lr을 살짝 낮출 수 있습니다.
training_args.learning_rate = 1e-5  # 예: 2e-5에서 1e-5로 하향 (선택사항)
training_args.num_train_epochs = 3 # 에포크 수는 유지하거나 상황에 맞게 조절

# 3. Trainer 생성 (수정된 train_dataset 주입)
# 여기서 새로운 train_dataset이 들어가야 모델이 '책상' 같은 오답을 학습합니다.
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
)

# 4. 재학습 시작
print("🚀 Hard Negative가 포함된 데이터로 학습을 다시 시작합니다...")
trainer.train()

# 1. 학습 데이터 10%만 샘플링
small_train_df = train_df.sample(frac=0.1, random_state=SEED)
# 2. 검증 데이터도 20% 정도만 샘플링 (평가 시간을 줄이기 위해)
small_val_df = val_df.sample(frac=0.2, random_state=SEED)

# 3. 데이터셋 다시 생성 (MAX_LENGTH를 128로 줄이면 더 빨라집니다!)
# 'input_with_context' 컬럼을 사용하는지 꼭 확인하세요!
train_dataset = QualityEvalDataset(small_train_df, tokenizer, max_length=330)
val_dataset = QualityEvalDataset(small_val_df, tokenizer, max_length=330)

# 4. Trainer 재선언 (새로운 데이터셋을 주입)
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset, # 줄어든 데이터셋
    eval_dataset=val_dataset,    # 줄어든 데이터셋
    compute_metrics=compute_metrics,
)

# 5. 학습 시작
print(f"🚀 샘플링 데이터({len(train_dataset)}개)로 쾌속 학습 시작...")
trainer.train()
print("✅ 학습 완료!")

"""## 10. 평가"""

# Validation 데이터로 평가
eval_results = trainer.evaluate()

print("=" * 50)
print("평가 결과")
print("=" * 50)
for key, value in eval_results.items():
    if 'loss' in key or 'f1' in key or 'match' in key:
        print(f"{key}: {value:.4f}")

# 기준별 정확도 출력
print("\n" + "=" * 50)
print("기준별 정확도")
print("=" * 50)
for criterion in CRITERIA:
    key = f'eval_{criterion}_acc'
    if key in eval_results:
        print(f"{criterion}: {eval_results[key]:.4f}")

"""## 11. 모델 저장"""

# 모델 저장
save_path = './outputs/klue-roberta-base-final'
trainer.save_model(save_path)
tokenizer.save_pretrained(save_path)

print(f"모델 저장 완료: {save_path}")

"""## 12. 추론 예시"""

## 추론용 입력 구성 함수

def format_input_with_history(history, current_question, current_response, window_size=2):
    """
    history: [{'q': '질문1', 'a': '답변1'}, {'q': '질문2', 'a': '답변2'}] 형태의 리스트
    """
    # 1. 최근 window_size만큼의 대화만 추출
    recent_history = history[-window_size:] if history else []

    # 2. [SEP]를 이용해 이전 맥락 생성
    history_text = ""
    for h in recent_history:
        history_text += f"{h['q']} [SEP] {h['a']} [SEP] "

    # 3. 최종 포맷팅: [이전 맥락] + 현재 질문 + [SEP] + 현재 답변
    full_input = f"{history_text}{current_question} [SEP] {current_response}"
    return full_input

def predict(text: str, model, tokenizer, device):
    """단일 텍스트에 대한 예측 수행"""
    model.eval()

    encoding = tokenizer(
        text,
        truncation=True,
        max_length=MAX_LENGTH,
        padding='max_length',
        return_tensors='pt'
    )

    encoding = {k: v.to(device) for k, v in encoding.items()}

    with torch.no_grad():
        outputs = model(**encoding)
        logits = outputs.logits
        probs = torch.sigmoid(logits).cpu().numpy()[0]
        preds = (probs > 0.5).astype(int)

    results = {}
    for i, criterion in enumerate(CRITERIA):
        results[criterion] = {
            'prediction': int(preds[i]),
            'probability': float(probs[i])
        }

    return results

# 1. 이전 대화 기록 (예시)
dialogue_history = [
    {"q": "요즘 볼만한 영화 추천해줘.", "a": "최근 개봉한 '인사이드 아웃 2'가 아주 인기예요!"},
    {"q": "그거 장르가 뭐야?", "a": "애니메이션이자 판타지 영화입니다. 감정들을 캐릭터화해서 어른들도 좋아해요."}
]

# 2. 현재 평가하고 싶은 질문과 응답
current_q = "그거 주인공 이름이 뭐야?"
current_a = "주인공의 이름은 '라일리'입니다. 이번 편에서는 새로운 감정인 '불안이'도 등장해요."

# 3. 학습 때와 동일한 포맷으로 병합 (window_size=2)
formatted_input = format_input_with_history(dialogue_history, current_q, current_a, window_size=2)

print(f"--- 모델 입력 텍스트 ---\n{formatted_input}\n")

# 4. 예측 수행
results = predict(formatted_input, model, tokenizer, device)

# 결과 출력 (기존과 동일)
print("=" * 50)
print(f"🙋 질문: {current_q}")
print(f"🤖 응답: {current_a}")
print("=" * 50)
for criterion, values in results.items():
    status = "✅" if values['prediction'] == 1 else "❌"
    print(f"{status} {criterion:25} | {values['probability']:.2%}")

# 추론 테스트
sample_question = "한국의 수도는 어디야?"
sample_response = "가나다라마바사"
sample_input = f"{sample_question} [SEP] {sample_response}"

print(f"질문: {sample_question}")
print(f"응답: {sample_response}")
print("\n" + "=" * 50)
print("예측 결과")
print("=" * 50)

results = predict(sample_input, model, tokenizer, device)
for criterion, values in results.items():
    status = "✓" if values['prediction'] == 1 else "✗"
    print(f"{status} {criterion}: {values['probability']:.2%}")

