# -*- coding: utf-8 -*-
"""Test_new2.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uAQBhJcYvh91cqbUO04Hkoy5rKHrSvnW

# AI 품질 평가 모델 학습 - klue/roberta-base

이 노트북은 AI 응답 품질 평가를 위한 Multi-label Classification 모델을 학습합니다.

**평가 기준 (9개)**:

- linguistic_acceptability (언어적 수용성)
- consistency (일관성)
- interestingness (흥미로움)
- unbias (편향 없음)
- harmlessness (무해성)
- no_hallucination (환각 없음)
- understandability (이해 가능성)
- sensibleness (합리성)
- specificity (구체성)

## 1. 라이브러리 설치 및 임포트
"""

# !pip install torch transformers datasets pandas scikit-learn tqdm -q

from google.colab import drive
drive.mount('/content/drive/')

import pandas as pd
import numpy as np
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
)
from sklearn.metrics import f1_score, accuracy_score
from tqdm.auto import tqdm
import warnings

warnings.filterwarnings('ignore')

# GPU 확인
device = torch.device('cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu')
print(f"Using device: {device}")

"""## 2. 설정"""

MODEL_NAME = "team-lucid/deberta-v3-base-korean" # 모델 변경
MAX_LENGTH = 330
BATCH_SIZE = 32 # DeBERTa는 메모리 점유율이 높아 배치 사이즈를 낮추는 것을 권장합니다.
LEARNING_RATE = 1e-5 # DeBERTa는 낮은 LR에서 안정적입니다.
NUM_EPOCHS = 3
SEED = 42

# 신규 설정 추가
EPSILON = 0.5 # FGM 노이즈 크기
ALPHA = 5.0   # R-Drop 가중치
SMOOTHING = 0.1 # Soft Labels

CRITERIA = [
    'linguistic_acceptability', 'consistency', 'interestingness',
    'unbias', 'harmlessness', 'no_hallucination',
    'understandability', 'sensibleness', 'specificity'
]
NUM_LABELS = len(CRITERIA)
torch.manual_seed(SEED)

"""## 3. 데이터 로드"""

# # unzip
# unzip_path = '/content/drive/MyDrive/AI_data/data.zip'
# !unzip -qq {unzip_path} -d /content/drive/MyDrive/AI_data/

# Training 및 Validation 데이터 로드 (aggregated 버전 사용 - majority voting 결과)
train_df = pd.read_csv('/content/drive/MyDrive/AI_data/data/train/training_all_aggregated.csv', encoding='utf-8-sig')
val_df = pd.read_csv('/content/drive/MyDrive/AI_data/data/val/validation_all_aggregated.csv', encoding='utf-8-sig')

print(f"Training 데이터: {len(train_df):,}개")
print(f"Validation 데이터: {len(val_df):,}개")

train_df['topic'].value_counts()

# 데이터 확인
train_df[train_df['topic']=='엔터테인먼트, 오락, 예술'].head(10)

# 1. 지표 매핑 딕셔너리 생성 (컬럼명: 한글 설명)
quality_metrics = {
    "linguistic_acceptability_majority": "언어학적 수용성",
    "consistency_majority": "일관성",
    "interestingness_majority": "흥미성",
    "unbias_majority": "비편향성",
    "harmlessness_majority": "무해성",
    "no_hallucination_majority": "정보 근거성",
    "understandability_majority": "이해 가능성",
    "sensibleness_majority": "답변의 적절성",
    "specificity_majority": "답변의 구체성"
}

target_topic = '엔터테인먼트, 오락, 예술'
entertainment_df = train_df[train_df['topic'] == target_topic]

for i, row in entertainment_df.tail(5).iterrows():
    print(f"[{i+1}번 데이터]")
    print(f"🙋 질문: {row['human_question']}")
    print(f"🤖 응답: {row['bot_response']}")
    print("\n[📊 품질 평가 상세]")

    # 9가지 지표를 순회하며 출력
    for col, name in quality_metrics.items():
        status = "✅ Pass" if row[col] == 1 else "❌ Fail"
        print(f" - {name}: {status}")

    print("-" * 50)

# 컬럼 확인
print("컬럼 목록:")
print(train_df.columns.tolist())

def create_hard_negatives(df, negative_ratio=0.2, seed=42):
    """기존 데이터의 답변을 섞어 '내용이 틀린' 부정 샘플을 생성합니다."""
    n_samples = int(len(df) * negative_ratio)
    neg_df = df.sample(n=n_samples, random_state=seed).copy()

    # 다른 행의 답변을 무작위로 가져와 매칭 (내용 불일치 유도)
    shuffled_responses = df.sample(n=n_samples, random_state=seed+1)['bot_response'].values
    neg_df['bot_response'] = shuffled_responses

    # 모든 품질 지표 라벨을 0(Fail)으로 설정
    for criterion in CRITERIA:
        neg_df[f"{criterion}_majority"] = 0

    print(f"✅ {n_samples}개의 Hard Negative 데이터 생성 완료!")
    return neg_df

import pandas as pd
from tqdm import tqdm
import numpy as np # 🆕 추가 (랜덤 시드 등을 위해 필요)

# 1. 기존 함수 유지
def merge_dialogue_context(df, window_size=2):

    df = df.sort_values(['conversation_id', 'utterance_index']).reset_index(drop=True)
    contexts = []
    for i in tqdm(range(len(df)), desc="Merging Contexts"):
        current_row = df.iloc[i]
        c_id = current_row['conversation_id']
        history = df[(df['conversation_id'] == c_id) & (df.index < i)].tail(window_size)
        history_text = ""
        for _, h_row in history.iterrows():
            history_text += f"{h_row['human_question']} [SEP] {h_row['bot_response']} [SEP] "
        full_input = f"{history_text}{current_row['human_question']} [SEP] {current_row['bot_response']}"
        contexts.append(full_input)
    df['input_with_context'] = contexts
    return df

# 2. 🆕 [함수 추가] Hard Negative 생성 함수
def create_hard_negatives(df, negative_ratio=0.2, seed=42):
    """기존 데이터의 답변을 섞어 '내용이 틀린' 부정 샘플을 생성합니다."""
    n_samples = int(len(df) * negative_ratio)
    neg_df = df.sample(n=n_samples, random_state=seed).copy()

    # 다른 행의 답변을 무작위로 가져와 매칭 (내용 불일치 유도)
    shuffled_responses = df.sample(n=n_samples, random_state=seed+1)['bot_response'].values
    neg_df['bot_response'] = shuffled_responses

    # 모든 품질 지표 라벨을 0(Fail)으로 설정
    for criterion in CRITERIA:
        neg_df[criterion] = 0
    return neg_df

# --- 적용하기 ---

# [변경 포인트 1] 학습 데이터 확장
print("🛠️ Hard Negative 데이터 생성 및 학습 데이터 확장 중...")
hard_neg_df = create_hard_negatives(train_df, negative_ratio=0.2)
# 기존 train_df와 생성된 부정 데이터를 합칩니다.
extended_train_df = pd.concat([train_df, hard_neg_df], axis=0, ignore_index=True)

# [변경 포인트 2] 확장된 데이터셋(extended_train_df)으로 맥락 병합 실행
print("학습 데이터 맥락 병합 중 (부정 샘플 포함)...")
train_df = merge_dialogue_context(extended_train_df, window_size=2)

# 검증 데이터는 원본 그대로 유지 (평가의 객관성을 위해)
print("검증 데이터 맥락 병합 중...")
val_df = merge_dialogue_context(val_df, window_size=2)

"""## 4. 데이터 전처리"""

def preprocess_data(df):
    df = df.copy()
    df['human_question'] = df['human_question'].fillna('')
    df['bot_response'] = df['bot_response'].fillna('')
    # Cross-Encoder 형식 구성
    df['input_text'] = df['human_question'] + ' [SEP] ' + df['bot_response']
    return df

train_df = preprocess_data(train_df)
val_df = preprocess_data(val_df)

print(f"전처리 후 Training 데이터: {len(train_df):,}개")
print(f"전처리 후 Validation 데이터: {len(val_df):,}개")

# 레이블 분포 확인
target_cols = [f'{c}_majority' for c in CRITERIA]

print("=" * 50)
print("레이블 분포 (Training)")
print("=" * 50)
for col in target_cols:
    pos_ratio = train_df[col].mean()
    print(f"{col}: {pos_ratio:.2%} positive")

"""## 5. Tokenizer 로드"""

!pip install huggingface_hub -q

from huggingface_hub import notebook_login
notebook_login() # 여기에 본인의 Hugging Face Access Token을 입력합니다.

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_auth_token=True)
# DeBERTa-v3는 내부적으로 특정 토큰 처리가 다르므로 반드시 해당 모델의 토크나이저를 써야 합니다.

print(f"Tokenizer 로드 완료: {MODEL_NAME}")
print(f"Vocab size: {tokenizer.vocab_size:,}")

# 토크나이저 테스트
sample_text = train_df['input_with_context'].iloc[0]
print(f"샘플 텍스트:\n{sample_text}\n")

tokens = tokenizer(sample_text, truncation=True, max_length=MAX_LENGTH)
print(f"토큰 수: {len(tokens['input_ids'])}")

# 1. 새로운 'input_with_context' 기준 토큰 길이 계산
token_lengths = [len(tokenizer.encode(text, add_special_tokens=True)) for text in tqdm(train_df['input_with_context'], desc="Checking New Lengths")]

# 2. 통계치 확인
print(f"\n[📊 맥락 포함 토큰 통계]")
print(f" - 95th percentile: {np.percentile(token_lengths, 95)}")
print(f" - 99th percentile: {np.percentile(token_lengths, 99)}")
print(f" - 최대 길이: {np.max(token_lengths)}")

# 3. 데이터 저장 (내일 바로 불러와서 쓸 수 있게)
# 구글 드라이브 경로로 설정하세요.
train_df.to_csv('/content/drive/MyDrive/final_train_context.csv', index=False)
val_df.to_csv('/content/drive/MyDrive/final_val_context.csv', index=False)
print("\n✅ 최종 데이터셋 저장 완료!")

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm

# 1. 모든 input_text의 토큰 길이 계산 (시간이 조금 걸릴 수 있습니다)
token_lengths = [len(tokenizer.encode(text, add_special_tokens=True)) for text in tqdm(train_df['input_with_context'], desc="Calculating lengths")]

# 2. 통계치 계산
max_len = np.max(token_lengths)
mean_len = np.mean(token_lengths)
p95 = np.percentile(token_lengths, 95)
p99 = np.percentile(token_lengths, 99)

print(f"\n[📊 Token Length Statistics]")
print(f" - 전체 데이터 수: {len(token_lengths)}개")
print(f" - 최대 토큰 길이: {max_len}")
print(f" - 평균 토큰 길이: {mean_len:.2f}")
print(f" - 95% 데이터가 포함되는 길이: {p95}")
print(f" - 99% 데이터가 포함되는 길이: {p99}")

# 3. 분포 시각화
plt.figure(figsize=(12, 6))
sns.histplot(token_lengths, bins=50, color='teal', kde=True)
plt.axvline(p95, color='orange', linestyle='--', label=f'95th Percentile ({p95:.0f})')
plt.axvline(p99, color='red', linestyle='--', label=f'99th Percentile ({p99:.0f})')
plt.title('Token Length Distribution (Question + Answer)')
plt.xlabel('Number of Tokens')
plt.ylabel('Count')
plt.legend()
plt.show()

"""## 6. Dataset 클래스 정의"""

class QualityEvalDataset(Dataset):
    def __init__(self, df, tokenizer, max_length=330, smoothing=0.1):
        self.df = df.reset_index(drop=True)
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.target_cols = [f'{c}_majority' for c in CRITERIA]
        self.smoothing = smoothing

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        # 수정: 'input_text' 대신 맥락이 포함된 'input_with_context' 사용
        text = row['input_with_context'] if 'input_with_context' in row else row['input_text']

        labels = row[self.target_cols].values.astype(np.float32)
        soft_labels = labels * (1.0 - self.smoothing) + (0.5 * self.smoothing)

        encoding = self.tokenizer(
            text, truncation=True, max_length=self.max_length,
            padding='max_length', return_tensors='pt'
        )
        return {
            'input_ids': encoding['input_ids'].squeeze(0),
            'attention_mask': encoding['attention_mask'].squeeze(0),
            'labels': torch.tensor(soft_labels, dtype=torch.float)
        }

# Dataset 생성
train_dataset = QualityEvalDataset(train_df, tokenizer, MAX_LENGTH)
val_dataset = QualityEvalDataset(val_df, tokenizer, MAX_LENGTH)

print(f"Train dataset size: {len(train_dataset):,}")
print(f"Val dataset size: {len(val_dataset):,}")

# Dataset 확인
sample = train_dataset[0]
print(f"input_ids shape: {sample['input_ids'].shape}")
print(f"attention_mask shape: {sample['attention_mask'].shape}")
print(f"labels shape: {sample['labels'].shape}")
print(f"labels: {sample['labels']}")

"""## 7. 모델 로드"""

# Multi-label Classification을 위한 모델 로드
model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME, num_labels=NUM_LABELS, problem_type="multi_label_classification"
)
model.to(device)
print(f"모델 로드 완료: {MODEL_NAME}")
print(f"파라미터 수: {sum(p.numel() for p in model.parameters()):,}")

"""## 8. 평가 지표 함수"""

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    probs = torch.sigmoid(torch.tensor(predictions)).numpy()
    preds = (probs > 0.5).astype(int)
    binary_labels = (labels > 0.5).astype(int)

    return {
        'exact_match': np.all(preds == binary_labels, axis=1).mean(),
        'macro_f1': f1_score(binary_labels, preds, average='macro', zero_division=0)
    }

"""## 9. Trainer 설정 및 학습"""

class FGM:
    def __init__(self, model):
        self.model = model
        self.backup = {}
    def attack(self, epsilon=0.5, emb_name='word_embeddings'):
        for name, param in self.model.named_parameters():
            if param.requires_grad and emb_name in name:
                self.backup[name] = param.data.clone()
                norm = torch.norm(param.grad)
                if norm != 0:
                    r_at = epsilon * param.grad / norm
                    param.data.add_(r_at)
    def restore(self, emb_name='word_embeddings'):
        for name, param in self.model.named_parameters():
            if param.requires_grad and emb_name in name:
                param.data = self.backup[name]
        self.backup = {}

# 1. CustomTrainer 완벽 구현 (R-Drop 포함)
class CustomTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        labels = inputs.get("labels")

        # R-Drop을 위해 모델을 두 번 통과 (서로 다른 드롭아웃 마스크 적용)
        outputs1 = model(**inputs)
        outputs2 = model(**inputs)

        logits1 = outputs1.get("logits")
        logits2 = outputs2.get("logits")

        # 기본 손실 (BCE)
        loss_fct = torch.nn.BCEWithLogitsLoss()
        loss1 = loss_fct(logits1, labels)
        loss2 = loss_fct(logits2, labels)
        base_loss = 0.5 * (loss1 + loss2)

        # R-Drop 손실 (KL-Divergence) 계산
        p1 = torch.sigmoid(logits1)
        p2 = torch.sigmoid(logits2)

        # 양방향 KL-Divergence
        kl_loss = F.kl_div(p1.log(), p2, reduction='batchmean') + \
                  F.kl_div(p2.log(), p1, reduction='batchmean')

        # 최종 손실 = BCE + alpha * KL
        total_loss = base_loss + ALPHA * (kl_loss / 4)

        return (total_loss, outputs1) if return_outputs else total_loss

def training_step(self, model, inputs, num_items_in_batch=None):
        model.train()
        inputs = self._prepare_inputs(inputs)

        # 1. 기본 손실 및 역전파
        loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
        # 수정 포인트: FP16(Mixed Precision) 호환을 위해 accelerator 사용
        self.accelerator.backward(loss)

        # 2. FGM 공격 (Adversarial Training)
        fgm = FGM(model)
        fgm.attack(epsilon=EPSILON)

        # 3. 적대적 손실 및 역전파
        loss_adv = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
        # 수정 포인트: FP16 호환을 위해 accelerator 사용
        self.accelerator.backward(loss_adv)

        fgm.restore()

        return loss.detach()

# 2. TrainingArguments 및 Trainer 설정
training_args = TrainingArguments(
    output_dir='./outputs/deberta-v3-quality',
    num_train_epochs=NUM_EPOCHS,
    per_device_train_batch_size=32,
    gradient_accumulation_steps=2,       # 2단계 누적하여 실질적 배치는 64 효과
    eval_strategy='epoch',
    save_strategy='epoch',
    load_best_model_at_end=True,
    metric_for_best_model='macro_f1',
    learning_rate=LEARNING_RATE,
    fp16=True,                          # 메모리 절약을 위해 필수
    logging_steps=50,
    seed=SEED
    )

# 3. 샘플링 데이터로 데이터셋 준비
small_train_df = train_df.sample(frac=0.1, random_state=SEED)
small_val_df = val_df.sample(frac=0.2, random_state=SEED)

train_dataset = QualityEvalDataset(small_train_df, tokenizer, max_length=MAX_LENGTH)
val_dataset = QualityEvalDataset(small_val_df, tokenizer, max_length=MAX_LENGTH)

# 4. 반드시 CustomTrainer로 선언!
trainer = CustomTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
)

print(f"🚀 DeBERTa-v3 + FGM + R-Drop 학습 시작...")
trainer.train()

# 1. 학습 데이터 10%만 샘플링
small_train_df = train_df.sample(frac=0.1, random_state=SEED)
# 2. 검증 데이터도 20% 정도만 샘플링 (평가 시간을 줄이기 위해)
small_val_df = val_df.sample(frac=0.2, random_state=SEED)

# 3. 데이터셋 다시 생성 (MAX_LENGTH를 128로 줄이면 더 빨라집니다!)
# 'input_with_context' 컬럼을 사용하는지 꼭 확인하세요!
train_dataset = QualityEvalDataset(small_train_df, tokenizer, max_length=330)
val_dataset = QualityEvalDataset(small_val_df, tokenizer, max_length=330)

# 4. Trainer 재선언 (새로운 데이터셋을 주입)
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset, # 줄어든 데이터셋
    eval_dataset=val_dataset,    # 줄어든 데이터셋
    compute_metrics=compute_metrics,
)

# 5. 학습 시작
print(f"🚀 샘플링 데이터({len(train_dataset)}개)로 쾌속 학습 시작...")
trainer.train()
print("✅ 학습 완료!")

"""## 10. 평가"""

# Validation 데이터로 평가
eval_results = trainer.evaluate()

print("=" * 50)
print("평가 결과")
print("=" * 50)
for key, value in eval_results.items():
    if 'loss' in key or 'f1' in key or 'match' in key:
        print(f"{key}: {value:.4f}")

# 기준별 정확도 출력
print("\n" + "=" * 50)
print("기준별 정확도")
print("=" * 50)
for criterion in CRITERIA:
    key = f'eval_{criterion}_acc'
    if key in eval_results:
        print(f"{criterion}: {eval_results[key]:.4f}")

"""## 11. 모델 저장"""

# 모델 저장
save_path = './outputs/klue-roberta-base-final'
trainer.save_model(save_path)
tokenizer.save_pretrained(save_path)

print(f"모델 저장 완료: {save_path}")

"""## 12. 추론 예시"""

## 추론용 입력 구성 함수

def format_input_with_history(history, current_question, current_response, window_size=2):
    """
    history: [{'q': '질문1', 'a': '답변1'}, {'q': '질문2', 'a': '답변2'}] 형태의 리스트
    """
    # 1. 최근 window_size만큼의 대화만 추출
    recent_history = history[-window_size:] if history else []

    # 2. [SEP]를 이용해 이전 맥락 생성
    history_text = ""
    for h in recent_history:
        history_text += f"{h['q']} [SEP] {h['a']} [SEP] "

    # 3. 최종 포맷팅: [이전 맥락] + 현재 질문 + [SEP] + 현재 답변
    full_input = f"{history_text}{current_question} [SEP] {current_response}"
    return full_input

def predict(text: str, model, tokenizer, device):
    """단일 텍스트에 대한 예측 수행"""
    model.eval()

    encoding = tokenizer(
        text,
        truncation=True,
        max_length=MAX_LENGTH,
        padding='max_length',
        return_tensors='pt'
    )

    encoding = {k: v.to(device) for k, v in encoding.items()}

    with torch.no_grad():
        outputs = model(**encoding)
        logits = outputs.logits
        probs = torch.sigmoid(logits).cpu().numpy()[0]
        preds = (probs > 0.5).astype(int)

    results = {}
    for i, criterion in enumerate(CRITERIA):
        results[criterion] = {
            'prediction': int(preds[i]),
            'probability': float(probs[i])
        }

    return results

# 1. 이전 대화 기록 (예시)
dialogue_history = [
    {"q": "요즘 볼만한 영화 추천해줘.", "a": "최근 개봉한 '인사이드 아웃 2'가 아주 인기예요!"},
    {"q": "그거 장르가 뭐야?", "a": "애니메이션이자 판타지 영화입니다. 감정들을 캐릭터화해서 어른들도 좋아해요."}
]

# 2. 현재 평가하고 싶은 질문과 응답
current_q = "그거 주인공 이름이 뭐야?"
current_a = "주인공의 이름은 '라일리'입니다. 이번 편에서는 새로운 감정인 '불안이'도 등장해요."

# 3. 학습 때와 동일한 포맷으로 병합 (window_size=2)
formatted_input = format_input_with_history(dialogue_history, current_q, current_a, window_size=2)

print(f"--- 모델 입력 텍스트 ---\n{formatted_input}\n")

# 4. 예측 수행
results = predict(formatted_input, model, tokenizer, device)

# 결과 출력 (기존과 동일)
print("=" * 50)
print(f"🙋 질문: {current_q}")
print(f"🤖 응답: {current_a}")
print("=" * 50)
for criterion, values in results.items():
    status = "✅" if values['prediction'] == 1 else "❌"
    print(f"{status} {criterion:25} | {values['probability']:.2%}")

# 추론 테스트
sample_question = "한국의 수도는 어디야?"
sample_response = "가나다라마바사"
sample_input = f"{sample_question} [SEP] {sample_response}"

print(f"질문: {sample_question}")
print(f"응답: {sample_response}")
print("\n" + "=" * 50)
print("예측 결과")
print("=" * 50)

results = predict(sample_input, model, tokenizer, device)
for criterion, values in results.items():
    status = "✓" if values['prediction'] == 1 else "✗"
    print(f"{status} {criterion}: {values['probability']:.2%}")

## 끝----