# -*- coding: utf-8 -*-
"""김보명_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xtQVIGsqJYtLY5oKaHSr4ctZdiS49JgR

# AI 품질 평가 모델 학습 - KLUE-RoBERTa-large
이 노트북은 AI 응답 품질 평가를 위한 Multi-label Classification 모델을 학습합니다.

평가 기준 (9개):

*   linguistic_acceptability (언어적 수용성)
*   consistency (일관성)
*   interestingness (흥미로움)
*   unbias (편향 없음)
*   harmlessness (무해성)
*   no_hallucination (환각 없음)
*   understandability (이해 가능성)
*   sensibleness (합리성)
*   specificity (구체성)

# 1. 라이브러리 설치 및 임포트
"""

!pip install torch transformers datasets pandas scikit-learn tqdm -q

from google.colab import drive
drive.mount('/content/drive/')

import pandas as pd
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
)
from sklearn.metrics import accuracy_score, f1_score, classification_report
from tqdm.auto import tqdm
from torch.utils.data import Dataset, Sampler
import warnings

warnings.filterwarnings('ignore')

# GPU 확인
device = torch.device('cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu')
print(f"Using device: {device}")

"""# 설정"""

# 모델 및 학습 설정
MODEL_NAME = "klue/roberta-base"
MAX_LENGTH = 256
BATCH_SIZE = 128
LEARNING_RATE = 2e-5
NUM_EPOCHS = 3
SEED = 42

# 평가 기준 (타겟 컬럼)
CRITERIA = [
    'linguistic_acceptability',
    'consistency',
    'interestingness',
    'unbias',
    'harmlessness',
    'no_hallucination',
    'understandability',
    'sensibleness',
    'specificity'
]
NUM_LABELS = len(CRITERIA)

# 시드 고정
torch.manual_seed(SEED)
np.random.seed(SEED)

train_df = pd.read_csv('/content/drive/MyDrive/ai_허브_데이터셋/data/train/training_all_aggregated.csv', encoding='utf-8-sig')
val_df = pd.read_csv('/content/drive/MyDrive/ai_허브_데이터셋/data/val/validation_all_aggregated.csv', encoding='utf-8-sig')

print(f"Training 데이터: {len(train_df):,}개")
print(f"Validation 데이터: {len(val_df):,}개")

print(train_df.iloc[0])

"""# 데이터의 투표 수 비율 변환 및 각 샘플의 난이도 수치화"""

def prepare_context_data(df, max_prev_turns=3):
    # 1. 정렬: 대화 세션별로 묶고 인덱스 순서대로 정렬 (에러 방지용Kind Stable 사용)
    df = df.sort_values(['conversation_id']).sort_index(kind='stable').reset_index(drop=True)

    # 2. '이전 질문 + 응답' 합친 텍스트 만들기 (QA 쌍 생성)
    df['qa_pair'] = "Q: " + df['human_question'].astype(str) + " A: " + df['bot_response'].astype(str)

    # 3. 그룹별로 이전 대화들을 리스트로 묶기
    def get_history(group):
        history = []
        res = []
        for i in range(len(group)):
            # 현재 행 기준, 이전 기록들의 복사본을 저장 (현재 행 QA는 제외)
            res.append(list(history))
            # 다음 행을 위해 현재 QA 쌍을 히스토리에 추가 (최대 턴수 유지)
            history.append(group.iloc[i]['qa_pair'])
            if len(history) > max_prev_turns:
                history.pop(0)
        return pd.Series(res, index=group.index)

    print("멀티턴 맥락(Context) 생성 중...")
    df['context'] = df.groupby('conversation_id', group_keys=False).apply(get_history)
    return df

# 데이터 로드 후 바로 실행
train_df = prepare_context_data(train_df)
val_df = prepare_context_data(val_df)

"""# 멀티턴 테스트"""

sample_id = train_df['conversation_id'].value_counts().index[0]
sample_session = train_df[train_df['conversation_id'] == sample_id][['conversation_id', 'human_question', 'bot_response', 'context']]

print(f"--- [Session ID: {sample_id}] 맥락 생성 확인 ---")
display(sample_session.head(5))

idx = train_df[train_df['context'].apply(len) >= 1].index[0] # 맥락이 있는 첫 데이터 찾기
row = train_df.iloc[idx]

context_text = " [SEP] ".join(row['context'])
full_text = f"{context_text} [SEP] {row['human_question']} [SEP] {row['bot_response']}"

print("--- [최종 모델 입력 형태 예시] ---")
print(full_text)

def preprocess_for_curriculum(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    # 1. 텍스트 결측치 처리 및 입력 텍스트 생성
    df['human_question'] = df['human_question'].fillna('')
    df['bot_response'] = df['bot_response'].fillna('')


    df['input_text'] = df['human_question'] + ' [SEP] ' + df['bot_response']

    # 2. Soft Labels 및 개별 난이도 계산
    # 각 행의 '전체 지표 난이도'를 합산할 변수를 초기화
    df['total_difficulty'] = 0

    for c in CRITERIA:
        # 투표 합계 계산
        total_votes = df[f'{c}_yes_count'] + df[f'{c}_no_count'] + 1e-8 #total_votes가 0일때 0으로 나누는 오류를 방지하기 위한 작은값

        # [Soft Label] 찬성 비율 계산 (0.0 ~ 1.0)
        df[f'{c}_soft'] = df[f'{c}_yes_count'] / total_votes

        # [난이도 측정] 만장일치 여부 확인
        # 3:0 혹은 0:3이면 쉬움(0), 2:1 혹은 1:2이면 어려움(1)으로 판단
        # 데이터셋에 이미 'unanimous' 컬럼이 있다면 활용하고, 없다면 직접 계산.
        is_hard = (df[f'{c}_yes_count'] > 0) & (df[f'{c}_no_count'] > 0)
        df['total_difficulty'] += is_hard.astype(int)

    # 3. 최종 난이도 점수 (0점: 매우 쉬움 ~ 9점: 매우 어려움)
    # 이 점수는 나중에 CurriculumSampler에서 학습 순서를 정하는 기준이 됨
    return df

# 전처리 실행
train_df = preprocess_for_curriculum(train_df)
val_df = preprocess_for_curriculum(val_df)

# 생성 결과 확인
print("--- 전처리 결과 샘플 (첫 5행) ---")
display(train_df[['input_text', 'total_difficulty'] + [f'{c}_soft' for c in CRITERIA[:2]]].head())

print(f"\n난이도 분포:\n{train_df['total_difficulty'].value_counts().sort_index()}")

# 가장 쉬운 데이터 1개 출력
print("--- [Easy] 난이도 0점 샘플 ---")
display(train_df[train_df['total_difficulty'] == 0][['input_text']].head(1))

# 가장 어려운 데이터 1개 출력
max_diff = train_df['total_difficulty'].max()
print(f"\n--- [Hard] 난이도 {max_diff}점 샘플 ---")
display(train_df[train_df['total_difficulty'] == max_diff][['input_text']].head(1))

"""# 텐서 가공"""

class MultiHeadSoftDataset(Dataset):
    """멀티턴 Context와 Soft Label을 지원하는 데이터셋"""
    def __init__(self, df, tokenizer, max_length=512): # 지침에 따라 길이를 512로 늘림
        self.df = df.reset_index(drop=True)
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.target_cols = [f'{c}_soft' for c in CRITERIA]

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        # 1. 맥락 연결: [이전 대화들] [SEP] [현재 질문] [SEP] [응답]
        context_list = row['context']
        context_text = " [SEP] ".join(context_list) if context_list else ""

        if context_text:
            full_text = f"{context_text} [SEP] {row['human_question']} [SEP] {row['bot_response']}"
        else:
            full_text = f"{row['human_question']} [SEP] {row['bot_response']}"

        # 2. 레이블 텐서 생성
        labels = torch.tensor(row[self.target_cols].values.astype(np.float32), dtype=torch.float)

        # 3. 토큰화 (멀티턴이므로 truncation은 앞쪽을 자르도록 설정 가능하나 기본은 뒤를 자름)
        encoding = self.tokenizer(
            full_text,
            truncation=True,
            max_length=self.max_length,
            padding='max_length',
            return_tensors='pt'
        )

        return {
            'input_ids': encoding['input_ids'].squeeze(0),
            'attention_mask': encoding['attention_mask'].squeeze(0),
            'labels': labels,
            'difficulty': torch.tensor(row['total_difficulty'], dtype=torch.float)
        }

class CurriculumSampler(Sampler):
    """에폭별로 신규 난이도는 100%, 이미 배운 난이도는 50%만 복습하는 샘플러"""
    def __init__(self, dataset_df, total_epochs, review_ratio=0.5):
        self.df = dataset_df
        self.total_epochs = total_epochs
        self.current_epoch = 0
        self.review_ratio = review_ratio # 복습 데이터 비중 (0.5 = 50%)

        # 난이도 점수(0~9점)를 미리 가져옵니다.
        self.difficulties = self.df['total_difficulty'].values

    def set_epoch(self, epoch):
        self.current_epoch = epoch

    def __iter__(self):
        # 1. 현재 에폭의 최대 난이도와 이전 에폭의 최대 난이도 계산
        current_max = ((self.current_epoch + 1) / self.total_epochs) * 9
        prev_max = (self.current_epoch / self.total_epochs) * 9 if self.current_epoch > 0 else -1

        # 2. 데이터 분류
        # [신규]: 이번 에폭에서 처음 배우는 난이도 구간
        new_indices = np.where((self.difficulties > prev_max) & (self.difficulties <= current_max))[0]
        # [복습]: 이전 에폭에서 이미 마스터한 난이도 구간
        old_indices = np.where(self.difficulties <= prev_max)[0]

        # 3. 복습 데이터만 50% 샘플링
        if len(old_indices) > 0:
            num_to_review = int(len(old_indices) * self.review_ratio)
            sampled_old_indices = np.random.choice(old_indices, num_to_review, replace=False)
        else:
            sampled_old_indices = np.array([], dtype=int)

        # 4. 신규 데이터 전체 + 샘플링된 복습 데이터 합치기
        final_indices = np.concatenate([new_indices, sampled_old_indices])

        # 무작위로 섞기
        np.random.shuffle(final_indices)

        print(f"\n[Curriculum] Epoch {self.current_epoch}: 신규 {len(new_indices):,}개 + 복습 {len(sampled_old_indices):,}개 = 총 {len(final_indices):,}개 학습")
        return iter(final_indices.tolist())

    def __len__(self):
        # __iter__와 동일한 개수 계산 로직
        current_max = ((self.current_epoch + 1) / self.total_epochs) * 9
        prev_max = (self.current_epoch / self.total_epochs) * 9 if self.current_epoch > 0 else -1

        new_count = len(np.where((self.difficulties > prev_max) & (self.difficulties <= current_max))[0])
        old_count = len(np.where(self.difficulties <= prev_max)[0])

        return new_count + int(old_count * self.review_ratio)

"""# 디코딩 테스트"""

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
test_dataset = MultiHeadSoftDataset(train_df, tokenizer, MAX_LENGTH)

sample = test_dataset[0]

print("--- 1. Decoding Test ---")
decoded_text = tokenizer.decode(sample['input_ids'], skip_special_tokens=False)
print(f"Decoded (with special tokens):\n{decoded_text[:150]}...")

"""# 레이블과 난이도가 잘 들어갔는지 테스트"""

print("\n--- 2. Label & Difficulty Test ---")
print(f"Label Tensor Shape: {sample['labels'].shape}")
print(f"Label Values: {sample['labels'].tolist()}")
print(f"Difficulty Score: {sample['difficulty'].item()}")

# 원본 데이터와 대조
print(f"Original Row Difficulty: {train_df.iloc[0]['total_difficulty']}")

"""# *`배치사이즈 잘 나왔는지 테스트`*"""

test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=True)
batch = next(iter(test_loader))

print("\n--- 3. Batch Shape Test ---")
print(f"Batch Input IDs Shape: {batch['input_ids'].shape}")
print(f"Batch Attention Mask Shape: {batch['attention_mask'].shape}")
print(f"Batch Labels Shape: {batch['labels'].shape}")
print(f"Batch Difficulty Shape: {batch['difficulty'].shape}")

"""# 모델 아키텍처"""

import torch.nn as nn
from transformers import AutoModel

class MultiHeadModel(nn.Module):
    def __init__(self, model_name='klue/roberta-base', num_criteria=9):
        super().__init__()
        # 1. Shared Backbone: 문맥 이해
        self.encoder = AutoModel.from_pretrained(model_name)
        self.hidden_size = self.encoder.config.hidden_size

        # 2. EDA 기반 그룹 정의
        # Group A: Content, Group B: Safety, Group C: Coherence, Group D: Independent
        self.criteria = CRITERIA # 9개 지표 리스트

        # 3. Task-Specific Heads: 각 지표별(9개ㅋ) 독립적인 판단
        self.heads = nn.ModuleDict({
            criterion: nn.Sequential(
                nn.Linear(self.hidden_size, 256),
                nn.GELU(),
                nn.Dropout(0.1),
                nn.Linear(256, 1)
            ) for criterion in self.criteria
        })

    def forward(self, input_ids, attention_mask):
        outputs = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        cls_output = outputs.last_hidden_state[:, 0, :] # [CLS] 토큰 활용

        # 각 헤드에서 결과 산출
        logits = [self.heads[c](cls_output) for c in self.criteria]
        return torch.cat(logits, dim=-1) # [batch_size, 9]

"""# custom Multi-loss"""

import torch.nn.functional as F

class FocalLoss(nn.Module):
    """불균형 대응용 Focal Loss (BCE 확장형)"""
    def __init__(self, gamma=2.0, alpha=0.25):
        super().__init__()
        self.gamma = gamma
        self.alpha = alpha

    def forward(self, logits, targets):
        probs = torch.sigmoid(logits)
        bce_loss = F.binary_cross_entropy_with_logits(logits, targets, reduction='none')
        p_t = probs * targets + (1 - probs) * (1 - targets)
        loss = bce_loss * ((1 - p_t) ** self.gamma)

        if self.alpha >= 0:
            alpha_t = self.alpha * targets + (1 - self.alpha) * (1 - targets)
            loss = alpha_t * loss
        return loss

class AsymmetricLoss(nn.Module):
    """극심한 불균형 대응용 Asymmetric Loss (ASL)"""
    def __init__(self, gamma_neg=4, gamma_pos=0, clip=0.05):
        super().__init__()
        self.gamma_neg = gamma_neg
        self.gamma_pos = gamma_pos
        self.clip = clip

    def forward(self, logits, targets):
        probs = torch.sigmoid(logits)

        # Positive Loss
        loss_pos = targets * torch.log(probs + 1e-8) * ((1 - probs) ** self.gamma_pos)

        # Negative Loss (with clipping)
        p_neg = (probs + self.clip).clamp(max=1)
        loss_neg = (1 - targets) * torch.log(1 - probs + 1e-8) * (p_neg ** self.gamma_neg)

        return -(loss_pos + loss_neg)

class CombinedLoss(nn.Module):
    def __init__(self):
        super().__init__()
        # 1. 지침에 따른 Loss 함수들 준비
        self.bce = nn.BCEWithLogitsLoss(reduction='none')
        self.focal = FocalLoss(gamma=2.0)
        self.asl = AsymmetricLoss(gamma_neg=4)

        # 2. 기준별 가중치 설정 (EDA 지침 3.1 준수)
        self.weights = torch.tensor([
            1.0, # linguistic_acceptability -> Soft BCE
            1.2, # consistency -> BCE
            0.8, # interestingness -> ASL
            1.0, # unbias -> Focal
            1.0, # harmlessness -> BCE
            2.0, # no_hallucination -> Soft BCE
            0.8, # understandability -> Focal
            1.0, # sensibleness -> Soft BCE
            0.8  # specificity -> ASL
        ]).to(device)

    def forward(self, logits, targets):
        batch_size = logits.size(0)
        num_criteria = logits.size(1)

        # 각 지표별로 계산된 Loss를 담을 리스트
        total_losses = []

        for i in range(num_criteria):
            crit_logits = logits[:, i]
            crit_targets = targets[:, i]

            # 3. 지표별 권장 Loss 매핑
            if i in [0, 5, 7]: # Soft BCE 그룹
                loss = self.bce(crit_logits, crit_targets)
            elif i in [1, 4]:  # 일반 BCE 그룹
                loss = self.bce(crit_logits, crit_targets)
            elif i in [3, 6]:  # Focal Loss 그룹 (불균형 대응)
                loss = self.focal(crit_logits, crit_targets)
            elif i in [2, 8]:  # ASL 그룹 (극심한 불균형 대응)
                loss = self.asl(crit_logits, crit_targets)

            # 가중치 곱하기
            total_losses.append(loss * self.weights[i])

        # 모든 지표의 Loss를 합산 후 평균
        combined_loss = torch.stack(total_losses).mean()
        return combined_loss

"""# 통합 학습 루프"""

from torch.optim import AdamW
from transformers import get_linear_schedule_with_warmup

# 1. 모델, 손실함수, 데이터셋 준비
model = MultiHeadModel(MODEL_NAME).to(device)
criterion = CombinedLoss()
train_dataset = MultiHeadSoftDataset(train_df, tokenizer, MAX_LENGTH)
val_dataset = MultiHeadSoftDataset(val_df, tokenizer, MAX_LENGTH)

# 2. 샘플러 및 데이터로더 설정
train_sampler = CurriculumSampler(train_df, total_epochs=NUM_EPOCHS)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE)

# 3. 옵티마이저 및 스케줄러 (학습률 관리)
optimizer = AdamW(model.parameters(), lr=LEARNING_RATE)
total_steps = len(train_df) // BATCH_SIZE * NUM_EPOCHS # 실제는 샘플러 때문에 더 적지만 최대치로 설정
scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=0, num_training_steps=total_steps)

# 4. 학습 루프 구현
def train_model():
    for epoch in range(NUM_EPOCHS):
        # [Curriculum] 에폭 설정 및 데이터로더 갱신
        train_sampler.set_epoch(epoch)
        train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, sampler=train_sampler)

        model.train()
        total_loss = 0

        for batch in tqdm(train_loader, desc=f"Epoch {epoch}"):
            optimizer.zero_grad()

            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)

            # Forward
            logits = model(input_ids, attention_mask)

            # Loss 계산 (EDA 가중치 반영된 CombinedLoss)
            loss = criterion(logits, labels)

            loss.backward()
            optimizer.step()
            scheduler.step()

            total_loss += loss.item()

        avg_loss = total_loss / len(train_loader)
        print(f"Epoch {epoch} Average Loss: {avg_loss:.4f}")

"""# 평기지표 계산"""

from sklearn.metrics import f1_score

def calculate_metrics(logits, labels):
    preds = (torch.sigmoid(logits) > 0.5).float().cpu().numpy()
    labels = (labels > 0.5).float().cpu().numpy()

    f1_list = []
    acc_list = [] # 정확도를 담을 바구니 추가

    for i in range(len(CRITERIA)):
        # 1. F1 Score 계산
        f1 = f1_score(labels[:, i], preds[:, i], average='macro', zero_division=0)
        f1_list.append(f1)

        # 2. Accuracy(정확도) 계산: 맞힌 개수 / 전체 개수
        acc = (labels[:, i] == preds[:, i]).mean()
        acc_list.append(acc)

    # 평균 F1, 상세 F1 리스트, 상세 정확도 리스트 3개를 돌려준다
    return np.mean(f1_list), f1_list, acc_list

# small_train_df = train_df.sample(n=100000, random_state=SEED).reset_index(drop=True)
# small_val_df = val_df.sample(n=20000, random_state=SEED).reset_index(drop=True)

# # 샘플용 데이터셋과 샘플러 다시 만들기
# small_train_dataset = MultiHeadSoftDataset(small_train_df, tokenizer, MAX_LENGTH)
# small_val_dataset = MultiHeadSoftDataset(small_val_df, tokenizer, MAX_LENGTH)
# small_train_sampler = CurriculumSampler(small_train_df, total_epochs=NUM_EPOCHS)

"""샘플링"""

print("--- [학습 데이터 난이도별 상세 분포] ---")
# 1. 각 점수별 정확한 개수
diff_counts = train_df['total_difficulty'].value_counts().sort_index()
print(diff_counts)

print("\n--- [에폭별 학습하게 될 데이터 양 예측] ---")
total_n = len(train_df)
for i in range(10): # 0점부터 9점까지
    count = len(train_df[train_df['total_difficulty'] <= i])
    percentage = (count / total_n) * 100
    print(f"난이도 {i} 이하 (누적): {count:>7,}개 | 전체의 {percentage:>6.2f}%")

# 에폭 0의 기준인 3.0점 확인
epoch_0_limit = 3.0
epoch_0_count = len(train_df[train_df['total_difficulty'] <= epoch_0_limit])
print(f"\n💡 에폭 0 (난이도 {epoch_0_limit} 이하) 실제 학습량: {epoch_0_count:,}개")

from torch.optim import AdamW
from transformers import get_linear_schedule_with_warmup

# --- [준비 단계] 모델 및 도구 초기화 ---
model = MultiHeadModel(MODEL_NAME).to(device)
criterion = CombinedLoss()
optimizer = AdamW(model.parameters(), lr=LEARNING_RATE)

# 데이터셋 및 샘플러 준비
train_dataset = MultiHeadSoftDataset(train_df, tokenizer, MAX_LENGTH)
val_dataset = MultiHeadSoftDataset(val_df, tokenizer, MAX_LENGTH)
train_sampler = CurriculumSampler(train_df, total_epochs=NUM_EPOCHS)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)

# --- [함수 정의] 학습 및 검증 엔진 ---
def train_and_eval(model, criterion, optimizer, train_dataset, val_dataset, train_sampler):
    # 그래프를 그리기 위한 기록 바구니
    history = {'loss': [], 'f1': []}

    for epoch in range(NUM_EPOCHS):
        # [Curriculum] 에폭 설정 및 데이터로더 동적 생성
        train_sampler.set_epoch(epoch)
        train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, sampler=train_sampler)

        # [A] 학습 단계 (Training)
        model.train()
        epoch_loss = 0

        for batch in tqdm(train_loader, desc=f"Epoch {epoch} Training"):
            optimizer.zero_grad()

            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)

            logits = model(input_ids, attention_mask)
            loss = criterion(logits, labels)

            loss.backward()
            optimizer.step()

            epoch_loss += loss.item()

        avg_loss = epoch_loss / len(train_loader)
        history['loss'].append(avg_loss)

        # [B] 검증 단계 (Validation)
        model.eval()
        all_logits = []
        all_labels = []

        with torch.no_grad():
            for batch in val_loader:
                logits = model(batch['input_ids'].to(device), batch['attention_mask'].to(device))
                all_logits.append(logits.cpu()) # 메모리 관리를 위해 cpu로 이동
                all_labels.append(batch['labels'].cpu())

        # 9개 지표의 상세 성적표 계산
        all_logits = torch.cat(all_logits, dim=0)
        all_labels = torch.cat(all_labels, dim=0)

        # 앞서 만든 채점기 호출
        mean_f1, f1_list, acc_list = calculate_metrics(all_logits, all_labels)
        history['f1'].append(mean_f1)

        # --- 상세 성적표 출력 ---
        print(f"\n" + "="*50)
        print(f"[Epoch {epoch}] 상세 성적표")
        print("-" * 50)
        for i, criterion_name in enumerate(CRITERIA):
            print(f"{criterion_name:25}: F1={f1_list[i]:.4f} | Acc={acc_list[i]:.2%}")
        print("-" * 50)
        print(f"전체 평균 F1: {mean_f1:.4f} | Loss: {avg_loss:.4f}")
        print("="*50 + "\n")

    return history # 학습 기록 반환

# 작은 데이터로 엔진 가동 테스트
print("---찐 학습 시작 ---")
# --- [실행]

history = train_and_eval(
    model,
    criterion,
    optimizer,
    train_dataset,
    val_dataset,
    train_sampler
)

# 1. 드라이브 내 저장 폴더 생성
import os
save_dir = '/content/drive/MyDrive/ai_허브_데이터셋'
if not os.path.exists(save_dir):
    os.makedirs(save_dir)

# 2. 모델 가중치 저장 (가장 중요!)
torch.save(model.state_dict(), os.path.join(save_dir, 'model_weights.pt'))

# 3. 토크나이저 저장
tokenizer.save_pretrained(save_dir)

print(f"구글 드라이브에 저장 완료: {save_dir}")

# 1. 모델 객체 새로 생성
import os
model = MultiHeadModel(MODEL_NAME).to(device)

# 2. 저장된 가중치 로드
save_dir = '/content/drive/MyDrive/ai_허브_데이터셋'
model.load_state_dict(torch.load(os.path.join(save_dir, 'model_weights.pt')))

# 3. 토크나이저 로드
tokenizer = AutoTokenizer.from_pretrained(save_dir)

# 4. 모델을 평가 모드로 전환
model.eval()

print("✅ 학습된 모델과 토크나이저를 성공적으로 불러왔습니다.")

# 검증 단계 (Validation) 로직만 실행
all_logits = []
all_labels = []

print("검증 데이터 평가 중...")
with torch.no_grad():
    for batch in tqdm(val_loader, desc="Evaluating"):
        logits = model(batch['input_ids'].to(device), batch['attention_mask'].to(device))
        all_logits.append(logits.cpu())
        all_labels.append(batch['labels'].cpu())

# 성적표 계산
all_logits = torch.cat(all_logits, dim=0)
all_labels = torch.cat(all_labels, dim=0)
mean_f1, f1_list, acc_list = calculate_metrics(all_logits, all_labels)

# --- 상세 성적표 출력 ---
print(f"\n" + "="*50)
print(f"[불러온 모델] 최종 검증 성적표")
print("-" * 50)
for i, criterion_name in enumerate(CRITERIA):
    print(f"{criterion_name:25}: F1={f1_list[i]:.4f} | Acc={acc_list[i]:.2%}")
print("-" * 50)
print(f"전체 평균 F1: {mean_f1:.4f}")
print("="*50 + "\n")

def predict_detailed(question, response, model, tokenizer):
    model.eval()
    # 1. 입력 텍스트 결합 (학습 때와 동일한 포맷)
    input_text = f"{question} [SEP] {response}"

    # 2. 토큰화 및 GPU 이동
    inputs = tokenizer(
        input_text,
        return_tensors='pt',
        padding='max_length',
        truncation=True,
        max_length=MAX_LENGTH
    ).to(device)

    # 3. 모델 추론
    with torch.no_grad():
        logits = model(inputs['input_ids'], inputs['attention_mask'])
        # 확률로 변환 (0~1 사이 소수점)
        probs = torch.sigmoid(logits).cpu().numpy()[0]
        # 0.5 기준으로 합격(1)/불합격(0) 판정
        preds = (probs > 0.5).astype(int)

    # 4. 결과 출력 (베이스 코드 스타일)
    print(f"\n" + "="*50)
    print(f"   [ AI 품질 평가 상세 추론 결과 ]")
    print("="*50)
    print(f"질문: {question}")
    print(f"응답: {response}")
    print("-" * 50)
    print(f"{'평가 항목':<25} | {'결과':<5} | {'확신도'}")
    print("-" * 50)

    for i, criterion in enumerate(CRITERIA):
        status = "✅ PASS" if preds[i] == 1 else "❌ FAIL"
        # 확신도가 높을수록 모델이 해당 결과에 자신있어 함
        confidence = probs[i] if preds[i] == 1 else (1 - probs[i])
        print(f"{criterion:<25} | {status:<5} | {probs[i]:.2%}")
    print("="*50 + "\n")

# --- 테스트 실행 예시 ---
q_test = "한국의 수도는 어디야?"
r_test = "한국의 수도는 멕시코입니다"

predict_detailed(q_test, r_test, model, tokenizer)